[package]
name = "aptos_social"
version = "1.0.0"
authors = []

[addresses]
aptos_social_addr = '_'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework"}

[dev-dependencies]
