export enum QueryKeys {
  Profile = 'profile',
  Collections = 'collections',
  Metadata = 'metadata',
  Posts = 'posts',
  Comments = 'comments',
  PostDetails = 'postDetails',
  NFTs = 'nfts',
  Hashtag = 'hashtag',
  Trends = 'trends',
  TrendingPosts = 'trendingposts',
  UsersToFollow = 'usersToFollow',
  Objects = 'objects',
  CollectionObjects = 'collectionObjects',
  AccountBalance = 'accountBalance',
  NFTMetadata = 'nftMetadata',
  Transactions = 'transactions',
  FungibleAssets = 'fungibleassets',
  Community = 'community',
  CommunityFeeds = 'communityFeeds',
  CollectibleAssets = 'collectibleassets',
  CollectedAssets = 'collectedassets',
  Replies = 'replies',
  Bookmarks = 'bookmarks',
}
